### ISSUE TITLE
Add 2019 and 2020 general election precinct results

### ISSUE THREAD

**Issue by ersawin** [openelections/openelections-results-va#2]
The 2019 and 2020 results are available at https://apps.elections.virginia.gov/SBE_CSV/ELECTIONS/ELECTIONRESULTS/2019/2019%20November%20General.csv and https://apps.elections.virginia.gov/SBE_CSV/ELECTIONS/ELECTIONRESULTS/2020/2020%20November%20General.csv, respectively. I am having trouble setting up the virtual environment to be able to run the loader to generate the precinct results files (seems like the build might be broken). If anyone is able to generate them, it would be very much appreciated!

**Comment by dwillis** [comment]
@ersawin got to this today, thanks for the nudge!

**Comment by ersawin** [comment]
Thanks a lot @dwillis!!
